# Generated by Django 3.0.8 on 2020-07-25 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='body',
            new_name='lowest_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='author',
            new_name='product_name',
        ),
    ]
